In [1]:
! pip install transformers==4.10.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 21.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 880.6/880.6 kB 45.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 21.0 MB/s eta 0:00:00
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895259 sha256=64d1b769317534856a2b5a755ee84172fc25882b863ba98f680351873882d67d
  Stored in directory: /root/.cache/pip/wheels/12/1c/3d/46cf06718d63a32ff798a89594b61e7f345ab6b36d909ce033
Successfully built sacremoses


# **Data**

In [2]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 17.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 20.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 10.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.3/269.3 kB 13.0 MB/s eta 0:00:00


# Emo Event dataset

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


emoevent_train_csv_path = '/content/drive/MyDrive/Colab Notebooks/emoevent_train.csv'
emoevent_dev_csv_path = '/content/drive/MyDrive/Colab Notebooks/emoevent_test.csv'

emoevent_train = pd.read_csv(emoevent_train_csv_path)
emoevent_dev = pd.read_csv(emoevent_dev_csv_path)



In [5]:
print('emoevent_train shape:', emoevent_train.shape)
emoevent_train.head(10)

emoevent_train shape: (5112, 2)


tweet  emotion
0  What is one thing that you can not live withou...        4
1  Hahahhaha bells will be ringing to show solida...        0
2  The Compassionate Civilization Collaborative (...        2
3  They say much was spared, but the images of HA...        5
4  "I may be small. I may be a girl, but I won’t ...        4
5  HASHTAG Today we have begun the definitive pha...        3
6  "The highest education is that which does not ...        4
7  “Hi Friends! Lots of people are making comment...        4
8  HASHTAG election: socialist party HASHTAG decl...        4
9  THAT EPISODE WAS FUCKING EVERYTHING... 🤯🤯🤯🤯🤯 H...        3

In [6]:
print('emoevent_train shape:', emoevent_train.shape)
emoevent_dev.head(10)

emoevent_train shape: (5112, 2)


tweet  emotion
0  Queen of Peace, look kindly upon the people an...        4
1  Very sad to see, as HASHTAG The French people ...        5
2  And they said Virgil Van Dijk is the best defe...        4
3  “The books that the world calls immoral are bo...        4
4  A short-circuit in the electrical system is mo...        4
5  US National Security advisor HASHTAG says that...        4
6  Theon, you're a good man. Thank you. HASHTAG H...        3
7  HASHTAG the baddest bitch in westeros HASHTAG ...        4
8  Let's take a moment to thank Melisandra for li...        3
9  HASHTAG Have you been troubled by your life? I...        4

In [7]:
emoevent_train['emotion'].head(10)

0    4
1    0
2    2
3    5
4    4
5    3
6    4
7    4
8    4
9    3
Name: emotion, dtype: int64

In [8]:
X_train = emoevent_train['tweet']
y_train = emoevent_train['emotion']

X_test = emoevent_dev['tweet']
y_test = emoevent_dev['emotion']

In [9]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(5112,)
(5112,)
(2191,)
(2191,)


In [10]:
# label: 'others': 0, 'joy': 6, 'disgust': 2, 'sadness': 3, 'anger': 4, 'surprise': 5, 'fear': 6
y_train.value_counts()

4    2313
3    1427
1     536
5     291
0     274
6     165
2     106
Name: emotion, dtype: int64

In [11]:
y_test.value_counts()

4    992
3    612
1    229
5    125
0    118
6     70
2     45
Name: emotion, dtype: int64

# **Model**


In [12]:
# Fit and transform X_train using Tfidf Vectorizer with default parameters
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train).toarray()
print('tfidf train shape:', X_train_tfidf.shape)
print('tfidf train type:', X_train_tfidf.dtype)

X_test_tfidf = vectorizer.transform(X_test).toarray()
print('tfidf test:', X_test_tfidf.shape)


tfidf train shape: (5112, 9912)
tfidf train type: float64
tfidf test: (2191, 9912)


In [13]:
from sklearn.svm import LinearSVC
clf = LinearSVC().fit(X_train_tfidf, y_train)

from sklearn import metrics
predicted = clf.predict(X_test_tfidf)

acc = metrics.accuracy_score(y_test, predicted)
print('accuracy is: ', acc*100)

from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predicted))
print('\n')
print(classification_report(y_test,predicted))

accuracy is:  53.40027384755819
[[  5  21   0   6  83   2   1]
 [ 14  48   2  21 138   4   2]
 [  1   3   1   3  36   1   0]
 [  0   7   0 354 239   8   4]
 [ 19  47   3 194 712  15   2]
 [  4   8   0  12  53  47   1]
 [  1   3   0  15  47   1   3]]


              precision    recall  f1-score   support

           0       0.11      0.04      0.06       118
           1       0.35      0.21      0.26       229
           2       0.17      0.02      0.04        45
           3       0.59      0.58      0.58       612
           4       0.54      0.72      0.62       992
           5       0.60      0.38      0.46       125
           6       0.23      0.04      0.07        70

    accuracy                           0.53      2191
   macro avg       0.37      0.28      0.30      2191
weighted avg       0.50      0.53      0.50      2191



# Augmentation using EDA

In [14]:
! pip install nlpaug==1.1.7

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.1/405.1 kB 9.0 MB/s eta 0:00:00


In [15]:
# apply augmentation to the train data and save the results into a file
import nlpaug.augmenter.char as nac
import nlpaug.augmenter.word as naw
import nlpaug.augmenter.sentence as nas
import nlpaug.flow as naf

from nlpaug.util import Action
import nlpaug.flow as naf

aug_eda = naf.Sequential([
    naf.Sometimes([naw.RandomWordAug(action="swap")]),
    naf.Sometimes([naw.RandomWordAug(action="delete")]),
    naf.Sometimes([naw.SynonymAug(aug_src='wordnet')])
])


In [16]:
import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [17]:
from tqdm.notebook import tqdm
tqdm.pandas()

data = {'text': X_train, 'label': y_train}
base_train = pd.DataFrame.from_dict(data)
base_train.shape

(5112, 2)

In [18]:
rep = 5 # how many repetitions of the record


eda_train = base_train.copy()
eda_train['paraphrase'] = eda_train['text'].progress_apply(lambda x:aug_eda.augment(x, rep))
eda_train = eda_train.explode('paraphrase').reset_index(drop=True)

  0%|          | 0/5112 [00:00<?, ?it/s]

KeyboardInterrupt: ignored

In [ ]:
eda_train.head(20)

text  label  \
0   What is one thing that you can not live withou...      4   
1   What is one thing that you can not live withou...      4   
2   What is one thing that you can not live withou...      4   
3   What is one thing that you can not live withou...      4   
4   What is one thing that you can not live withou...      4   
5   Hahahhaha bells will be ringing to show solida...      0   
6   Hahahhaha bells will be ringing to show solida...      0   
7   Hahahhaha bells will be ringing to show solida...      0   
8   Hahahhaha bells will be ringing to show solida...      0   
9   Hahahhaha bells will be ringing to show solida...      0   
10  The Compassionate Civilization Collaborative (...      2   
11  The Compassionate Civilization Collaborative (...      2   
12  The Compassionate Civilization Collaborative (...      2   
13  The Compassionate Civilization Collaborative (...      2   
14  The Compassionate Civilization Collaborative (...      2   
15  They say much was spared, but the images of HA...      5   
16  They say much was spared, but the images of HA...      5   
17  They say much was spared, but the images of HA...      5   
18  They say much was spared, but the images of HA...      5   
19  They say much was spared, but the images of HA...      5   

                                           paraphrase  
0   What is i thing that you can not live without?...  
1   What matchless thing you can live? — Easy, uni...  
2   What is unrivaled that can non live without? E...  
3   Is that you can not live without? — Easy, HASH...  
4   Is what one thing you without? — Easy, HASHTAG...  
5   Hahahhaha bells be exhibit solidarity for HASH...  
6   Hahahhaha bells be ringing solidarity for HASH...  
7   Hahahhaha bells bequeath be to present for HAS...  
8   Bells will be show HASHTAG! Been telling for p...  
9   Hahahhaha bells will ringing be show to solida...  
10  The Compassionate Collaborative Civilization (...  
11  The Compassionate Civilization Collaborative (...  
12  The Compassionate Collaborative (C3) has decla...  
13  The Civilization Collaborative () declared a /...  
14  The Civilisation Collaborative (C3) climate / ...  
15  They say much was spared, images HASHTAG up in...  
16  They a great deal say spar was but, the of ima...  
17  Say they much be spared, simply of images the ...  
18  They say much was spared, only the images of H...  
19  Say they much spared was, the but images of up...

# Model with augmented train data (paraphrased data)

In [ ]:
# Fit and transform X_train using Tfidf Vectorizer with default parameters
from sklearn.feature_extraction.text import TfidfVectorizer

# !! we should concatenate original train with paraphrased train
new_data = X_train.append(eda_train['paraphrase'])

vectorizer = TfidfVectorizer() #max_features=3000)
X_train_tfidf = vectorizer.fit_transform(new_data).toarray() #eda_train['paraphrase']).toarray()
print('tfidf train shape:', X_train_tfidf.shape)
print('tfidf train type:', X_train_tfidf.dtype)

X_test_tfidf = vectorizer.transform(X_test).toarray()
print('tfidf test:', X_test_tfidf.shape)


<ipython-input-26-32f711c08426>:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_data = X_train.append(eda_train['paraphrase'])


tfidf train shape: (30672, 15143)
tfidf train type: float64
tfidf test: (2191, 15143)


In [ ]:
from sklearn.svm import LinearSVC
# !! we should concatenate original labels with paraphrased text labels
new_labels = y_train.append(eda_train['label'])

clf = LinearSVC().fit(X_train_tfidf, new_labels) # eda_train['label'])

from sklearn import metrics
predicted = clf.predict(X_test_tfidf)

acc = metrics.accuracy_score(y_test, predicted)
print('accuracy is: ', acc*100)

from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predicted))
print('\n')
print(classification_report(y_test,predicted))

<ipython-input-27-e631ece76bc9>:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_labels = y_train.append(eda_train['label'])


accuracy is:  49.88589685075308
[[ 12  22   1   9  69   4   1]
 [ 15  57   3  18 128   6   2]
 [  1   3   2   4  34   1   0]
 [  0  11   0 337 244  14   6]
 [ 24  73   6 227 632  21   9]
 [  3  12   0  10  52  47   1]
 [  5   4   0  13  38   4   6]]


              precision    recall  f1-score   support

           0       0.20      0.10      0.13       118
           1       0.31      0.25      0.28       229
           2       0.17      0.04      0.07        45
           3       0.55      0.55      0.55       612
           4       0.53      0.64      0.58       992
           5       0.48      0.38      0.42       125
           6       0.24      0.09      0.13        70

    accuracy                           0.50      2191
   macro avg       0.35      0.29      0.31      2191
weighted avg       0.47      0.50      0.48      2191



# Create CSV file from augmented dataset

In [ ]:
!cd '/content/drive/My Drive/Colab Notebooks/'
eda_train.to_csv('/content/drive/My Drive/Colab Notebooks/EmoEvent_EdaAug_5.csv', encoding='utf-8', index=False, sep=',')